name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin  
          docker build . --file ./PortainerSample/Dockerfile --tag portainer-sample:$(date +%s) --tag ghcr.io/slothman5566/portainer-sample:latest
          docker push ghcr.io/slothman5566/portainer-sample:latest
