name: Attach ZIP to Release

on:
  release:
    types:
      - published  # 監聽 "已發布的 Release"

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ 生成 ZIP 檔案
      - name: Build & Package
        run: |
          mkdir -p output
          echo "Hello, world!" > output/hello.txt
          zip -r package.zip output

      # 2️⃣ 上傳 ZIP 到 Release
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./package.zip
          asset_name: package.zip
          asset_content_type: application/zip
